[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "elt-lakehouse"
version = "0.1.0"
requires-python = ">=3.10"
description = "ELT Lakehouse data engineering project"

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]
include = ["elt_lakehouse*"]
