---
spark:
  app_name: Modern Lakehouse
  bronze:
    compression: snappy
    mode: overwrite
  delta:
    enable: true
  master: local[*]
  sql:
    shuffle_partitions: 4
    timezone: UTC
  storage:
    bronze: storage/bronze
    generated: storage/generated
    gold: storage/gold
    silver: storage/silver