---
spark:
  app_name: Modern Lakehouse
  bronze:
    compression: snappy
    mode: overwrite
  delta:
    enable: true
  master: local[8]
  memory:
    driver: 4g
    executor: 4g
  sql:
    shuffle_partitions: 4
    maxPartitionBytes: 67108864
    timezone: UTC
  storage:
    bronze: storage/bronze
    generated: storage/generated
    gold: storage/gold
    silver: storage/silver