spark:
  app_name: Modern Lakehouse
  master: local[*]

  sql:
    shuffle_partitions: 4
    timezone: "UTC"

  delta:
    enable: true
  
  storage:
    generated: "storage/generated"
    bronze: "storage/bronze"
    silver: "storage/silver"
    gold: "storage/gold"
  
  bronze:
    mode : overwrite
    compression : "snappy"